name: Gataria CI/CD Dev
on:
  push:
    branches:
      - dev

jobs:
  build-dev:
    name: Build dev
    if: contains(github.ref, 'dev') 
    runs-on: self-hosted
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        run: docker build -t evermariano/gataria-backend-catalog:dev$GITHUB_SHA . 
      - name: docker push
        run: docker push evermariano/gataria-backend-catalog:dev$GITHUB_SHA

  test-dev:
    name: Test dev
    if: contains(github.ref, 'dev') 
    runs-on: self-hosted
    needs: build-dev
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: running tests
        run: npm test

  deploy-dev:
    name: Deploy dev
    if: contains(github.ref, 'dev') 
    runs-on: self-hosted
    needs: test-dev
    container:
      image: evermariano/gataria-deploy:1.0.0
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Add ChartMuseum Repo
        run: helm repo add gataria-charts http://chartmuseum:8080
      - name: Helm update repo
        run: helm repo update
      - name: Deploy dev
        run: helm upgrade gataria-backend-catalog gataria-charts/gataria-backend-catalog -n dev --set image.tag=dev$GITHUB_SHA --set "ingress.hosts[0].host=dev.gataria.example" --set "ingress.hosts[0].paths[0].path=/catalog" --set "ingress.hosts[0].paths[0].pathType=Prefix" || helm install gataria-backend-catalog gataria-charts/gataria-backend-catalog -n dev --set image.tag=dev$GITHUB_SHA --set "ingress.hosts[0].host=dev.gataria.example" --set "ingress.hosts[0].paths[0].path=/catalog" --set "ingress.hosts[0].paths[0].pathType=Prefix"
